services:
  web:
    build:
      context: ../frontend/web
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - frontend-network
      - backend-network

  app:
    build:
      context: ../backend/FlyCheap.App/FlyCheap.API
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - backend-network
      - database-network

  mysql:
    image: mysql
    env_file:
      - ./.env
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - database-network

volumes:
  mysql-data:
    driver: local

networks:
  frontend-network:
    driver: bridge
  backend-network:
    driver: bridge
  database-network:
    driver: bridge
